#注册服务        
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    # 心跳间隔 默认30秒
    lease-renewal-interval-in-seconds: 10
  client:
    #  向服务器发起注册
    register-with-eureka: true
    #  循环检索注册服务
    fetch-registry: true
    #  定义从注册中心获取注册服务的信息 默认30秒
    registry-fetch-interval-seconds: 10
    #  注册服务地址
    service-url:
      defaultZone: http://huolika:huolika2019@10.29.26.201:9001/eureka/eureka/,http://huolika:huolika2019@10.29.26.117:9001/eureka/eureka/

# spring datasource config
spring:
  application:
    name: sms
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 172.19.57.211:9300
  datasource:
    name: beadwalletloan
    url: jdbc:mysql://rm-uf6s0j8g14m247250.mysql.rds.aliyuncs.com:3306/huolika?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&rewriteBatchedStatements=true
    username: huolika_app
    password: huolika@2019
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 4
      max-active: 32
      max-wait: 60000
      min-idle: 4
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      test-while-idle: true
      validation-query: select 1

#spring-session 使用
  session:
    store-type: none
# Redis jedis配置
  redis:
# Redis数据库索引（默认为0）
    database: 6
# Redis服务器地址
    host: 9686e0ac66ee45b2.redis.rds.aliyuncs.com
# Redis服务器连接端口
    port: 6379
# Redis服务器连接密码（默认为空）
    password: 9686e0ac66ee45b2:BeadWallet2016
# 连接超时时间（毫秒）
    timeout: 100000
# 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 500
        max-idle: 5
        min-idle: 1
        max-wait: 100000
  # 模板引擎
  thymeleaf:
    # 禁用缓存
    cache: false

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10